version: "3"
services:
  app:
    container_name: boot-cms-docker-compose
    image: boot-cms-docker-compose
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/cms
  db:
    image: postgres:14.2-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cms


